name: complex

on:
  push:
    branches: ['master']

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: docker
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: docker build
        run: docker build -t phamtuan239/react-test -f ./client/Dockerfile.dev ./client
      - name: docker run
        run: docker run -e CI=true phamtuan239/react-test npm run test
      - name: docker after run
        run: |
          - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          - docker build -t phamtuan239/multi-client ./client
          - docker build -t phamtuan239/multi-backend ./backend
          - docker build -t phamtuan239/multi-nginx ./nginx
          - docker build -t phamtuan239/multi-worker ./worker
          - docker push phamtuan239/multi-client
          - docker push phamtuan239/multi-backend
          - docker push phamtuan239/multi-nginx
          - docker push phamtuan239/multi-worker
