name: complex

on:
  push:
    branches: ['master']

env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: docker
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: docker build
        run: docker build -t travis99/react-test -f ./client/Dockerfile.dev ./client

      - name: docker run
        run: docker run -e CI=true travis99/react-test npm run test

      - name: docker after run
        run: |
          docker build -t travis99/multi-client ./client
          docker build -t travis99/multi-backend ./backend
          docker build -t travis99/multi-nginx ./nginx
          docker build -t travis99/multi-worker ./worker
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker push travis99/multi-client
          docker push travis99/multi-backend
          docker push travis99/multi-nginx
          docker push travis99/multi-worker

      - name: Get timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%s')"

      - name: Generate deployment package
        run: zip -r Complex-Docker.zip . -x '*.git*' -x '**node_modules**'

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: '${{ steps.current-time.outputs.time }}'
          replace-with: '-'
          flags: 'g'

      - name: deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: complex
          environment_name: Complex-env
          region: ap-southeast-1
          existing_bucket_name: elasticbeanstalk-ap-southeast-1-891869786502
          version_label: Complex-Docker-${{ steps.format-time.outputs.replaced }}
          deployment_package: Complex-Docker.zip
          use_existing_version_if_available: true    